[package]
name = "sonos"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
upnp = { path = "../upnp" }
futures-util = "0.3"
roxmltree = "0.7"

[dev-dependencies]
async-std = "0.99"
futures = "0.3"
