[package]
name = "sonos"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
failure = "0.1"
futures = "0.1"

hyper = "0.12"

marksman_escape = "0.1.2"

serde = { version = "1.0", features = ["derive"] }
xmltree = "0.8.0"

[dependencies.upnp]
path = "../upnp"

[dependencies.upnp_zoneplayer1]
path = "../upnp_zoneplayer1"