[package]
name = "sonos"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
upnp = { path = "../upnp" }
futures-util = { version = "0.3", default-features = false }
roxmltree = "0.7"

[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
futures = "0.3"
